#!/usr/bin/python3
''' main program. This will handle just the parsing of options
and then it will generate a Puppet object	

if we want to get an alligator character who says 'hello world' in 
blue ink we will run it like this :

xkaasay -c alligator -a say -t 'Hello World!' -i blue '''

import os
import sys
import argparse
import xkaa 

# Define color constants
COLORS = {
    'black': (0, 0, 0),
    'red': (255, 0, 0),
    'blue': (0, 0, 255),
    'green': (0, 255, 0)
}

def parse_color(color_value):
    """Parse color from string or named color"""
    if isinstance(color_value, str):
        # Try as a named color first
        if color_value.lower() in COLORS:
            return COLORS[color_value.lower()]
        
        # Try parsing as RGB values
        try:
            color_str = color_value.strip('()')
            r, g, b = map(int, color_str.split(','))
            return (r, g, b)
        except:
            return COLORS['black']
    
    return COLORS['black']

def main():
    parser = argparse.ArgumentParser(description='Display a character with a speech bubble')
    parser.add_argument('-t', '--text', 
                       default="Hello World! Use -h for help",
                       help="Your text")
    parser.add_argument('-a', '--action',
                       default="say",
                       help="action can be: say, shout, think or dream")
    parser.add_argument('-d', '--dream',
                       default="images/sheep.png",
                       help="path to dream image")
    parser.add_argument('-c', '--character',
                       default="snake",
                       help="character name")
    parser.add_argument('-i', '--color',
                       default="black",
                       help="ink color (name or R,G,B values)")

    args = parser.parse_args()
    
    # Parse the color
    color = parse_color(args.color)

    # Create and run the puppet
    app = xkaa.Puppet(
        character=args.character,
        verb=args.action,
        text=args.text,
        dreamed=args.dream,
        font="BonvenoCF-Light.otf",
        fontcolor=color
    )
    app.mainloop()

if __name__ == "__main__":
    main()
