#!/usr/bin/python3
''' main program. This will handle just the parsing of options
and then it will generate a Puppet object

if we want to get an alligator character who says 'hello world' in
blue ink we will run it like this :

xkaasay -c alligator -a say -t 'Hello World!' -i blue '''



import os
import sys
import argparse
import xkaa

black = (0, 0, 0)
red = (255, 0, 0)
blue = (0, 0, 255)
green = (0, 255, 0)

# Color mapping for string inputs
color_map = {
	'black': black,
	'red': red,
	'blue': blue,
	'green': green
}

parser = argparse.ArgumentParser(description='xKaa - A fun character speech bubble display')
parser.add_argument('-t', '--text', action="store", default="Hello World! Use -h for help", help="Your text")
parser.add_argument('-a', '--action', action="store", default="say", help="action can be: say, shout, think or dream")
parser.add_argument('-d', '--dream', action="store", default="images/sheep.png", help="path to dream image")
parser.add_argument('-c', '--character', action="store", default="snake", help="character name")
parser.add_argument('-i', '--ink', action="store", default='black', help="ink color (black, red, blue, green)")

args = parser.parse_args()

# Convert ink color from string to tuple if needed
ink_color = color_map.get(args.ink, black)

xkaa.Puppet(character=args.character, verb=args.action, text=args.text, dreamed=args.dream, font="BonvenoCF-Light.otf", fontcolor=ink_color)

